"""news tables

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('month')
    )
    op.create_table('news_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_title', sa.String(length=500), nullable=False),
    sa.Column('first_published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_clusters_first_published_at'), ['first_published_at'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('url_normalized', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.String(length=300), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_clusters.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_url_normalized'), ['url_normalized'], unique=False)

    op.create_table('sentiments',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_clusters.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_table('news_instruments',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_clusters.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('cluster_id', 'instrument_id')
    )
    with op.batch_alter_table('news_instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_instruments_instrument_id'), ['instrument_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_instruments_instrument_id'))

    op.drop_table('news_instruments')
    op.drop_table('sentiments')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_url_normalized'))
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_cluster_id'))

    op.drop_table('news_items')
    with op.batch_alter_table('news_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_clusters_first_published_at'))

    op.drop_table('news_clusters')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
