"""indicator events and move links

Revision ID: 0004
Revises: 0003
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=3), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('algo_version', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'type', 'direction', 'ts_utc', 'algo_version')
    )
    with op.batch_alter_table('indicator_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicator_events_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index('ix_indicator_events_lookup', ['instrument_id', 'timeframe', 'ts_utc'], unique=False)

    op.create_table('notable_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=3), nullable=False),
    sa.Column('move_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('move_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('return_z', sa.Float(), nullable=True),
    sa.Column('volume_z', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('algo_version', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'move_start', 'algo_version')
    )
    with op.batch_alter_table('notable_moves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notable_moves_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('move_news_links',
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('time_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_clusters.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['notable_moves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('move_id', 'cluster_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move_news_links')
    with op.batch_alter_table('notable_moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notable_moves_instrument_id'))

    op.drop_table('notable_moves')
    with op.batch_alter_table('indicator_events', schema=None) as batch_op:
        batch_op.drop_index('ix_indicator_events_lookup')
        batch_op.drop_index(batch_op.f('ix_indicator_events_instrument_id'))

    op.drop_table('indicator_events')
    # ### end Alembic commands ###
