"""pattern detections, zones, backtest runs

Revision ID: 0005
Revises: 0004
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=3), nullable=False),
    sa.Column('algo_version', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('universe', sa.Text(), nullable=False),
    sa.Column('date_range', sa.String(length=100), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('ci_low', sa.Float(), nullable=True),
    sa.Column('ci_high', sa.Float(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('code_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_runs_lookup', ['kind', 'subject', 'timeframe', 'algo_version', 'created_at'], unique=False)

    op.create_table('pattern_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=3), nullable=False),
    sa.Column('pattern_type', sa.String(length=30), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('formed_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breakout_direction', sa.String(length=10), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON(), nullable=False),
    sa.Column('confirmation_level', sa.Float(), nullable=False),
    sa.Column('invalidation_level', sa.Float(), nullable=False),
    sa.Column('scenarios', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('params_hash', sa.String(length=16), nullable=False),
    sa.Column('algo_version', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'fingerprint')
    )
    with op.batch_alter_table('pattern_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pattern_detections_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index('ix_pattern_detections_lookup', ['instrument_id', 'timeframe', 'end_ts'], unique=False)

    op.create_table('pattern_scans',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=3), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bars_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bars_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recent_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bar_count', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('params_hash', sa.String(length=16), nullable=False),
    sa.Column('algo_version', sa.String(length=20), nullable=False),
    sa.Column('empty_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'timeframe')
    )
    op.create_table('sr_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=3), nullable=False),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('lower', sa.Float(), nullable=False),
    sa.Column('upper', sa.Float(), nullable=False),
    sa.Column('touches', sa.JSON(), nullable=False),
    sa.Column('first_touch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_touch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('params_hash', sa.String(length=16), nullable=False),
    sa.Column('algo_version', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sr_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sr_zones_instrument_id'), ['instrument_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sr_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sr_zones_instrument_id'))

    op.drop_table('sr_zones')
    op.drop_table('pattern_scans')
    with op.batch_alter_table('pattern_detections', schema=None) as batch_op:
        batch_op.drop_index('ix_pattern_detections_lookup')
        batch_op.drop_index(batch_op.f('ix_pattern_detections_instrument_id'))

    op.drop_table('pattern_detections')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_runs_lookup')

    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
